server:
  port: 9020
  servlet.context-path: /oss-local

spring:
  application:
    name: springseed-oss-local-server
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    format-sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oss_local?characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          # 需要在host文件中定义auth-server服务地址
          issuer-uri: http://auth-server:9000/auth/realms/springseeds
          jwk-set-uri: http://auth-server:9000/auth/realms/springseeds/protocol/openid-connect/certs
  servlet:
    # 文件上传
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 150MB

# 日志配置
logging:
  level:
    ROOT: INFO
    "[org.springseed]": DEBUG    
    "[org.springframework.security]": DEBUG
    "[org.springframework.web]": DEBUG

