server:
  port: 9020
  servlet.context-path: /oss-minio

springseed.oss.minio:
  server:
    endpoint: 127.0.0.1
    port: 8001
    accessKey: admin
    secretKey: 12345678

spring:
  application:
    name: springseed-oss-minio-server
  security:
    oauth2:
      resourceserver:
        jwt:
          # 需要在host文件中定义auth-server服务地址
          issuer-uri: http://auth-server:9000/auth/realms/springseeds
          jwk-set-uri: http://auth-server:9000/auth/realms/springseeds/protocol/openid-connect/certs
  servlet:
    # 文件上传
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 150MB

# 日志配置
logging:
  level:
    ROOT: INFO
    "[org.springseed]": DEBUG    
    "[org.springframework.security]": DEBUG
    "[org.springframework.web]": DEBUG

