server:
  port: 9030
  servlet.context-path: /activiti

spring:
  application:
    name: springseed-activiti-server
  # JPA配置
  # jpa:
  #   database-platform: org.hibernate.dialect.MySQL8Dialect
  #   show-sql: true
  #   format-sql: true
  #   open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti?characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          # 需要在host文件中定义auth-server服务地址
          issuer-uri: http://auth-server:9000/auth/realms/springseeds
          jwk-set-uri: http://auth-server:9000/auth/realms/springseeds/protocol/openid-connect/certs

# 日志配置
logging:
  level:
    ROOT: INFO
    "[org.springseed]": INFO    
    "[org.springframework.security]": INFO
    "[org.springframework.messaging]": DEBUG
    # "[org.springframework.cache]": TRACE
