server:
  port: 9001  

spring:
  application:
    name: springseed-resource
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    format-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
       ddl-auto: create
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springseeds?characterEncoding=UTF-8&useSSL=true
    username: springseeds
    password: springseeds
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/auth/realms/springseeds
          jwk-set-uri: http://localhost:9000/auth/realms/springseeds/protocol/openid-connect/certs

# 日志配置
logging:
  level:
    ROOT: INFO
    # "[org.springframework.security]": DEBUG
    # "[org.springframework.cache]": TRACE
    # "[org.keycloak]": TRACE
