server:
  port: 9001

spring:
  application:
    name: springseed-mail
  mail:
    default-encoding: UTF-8
    username: 44010039@qq.com
    # 授权码
    password: xxxxxxyyyyyy    
    host: smtp.qq.com
    properties: 
      mail:
        smtp:
          ssl:
            enable: true  